### ISSUE TITLE
Crash when valid generic jenkins url is pasted instead of build url

### ISSUE THREAD

**Issue by Artalus** [Artalus/jenot#33]
```
2022-03-22 15:07:52,913 - ERROR - failed to parse api response; got this:
_class: org.jenkinsci.plugins.workflow.job.WorkflowJob
buildable: true
builds:
- _class: org.jenkinsci.plugins.workflow.job.WorkflowRun
  number: 138
...

Traceback (most recent call last):
  File "/mnt/filedump/git/jenot/src/jenot/__init__.py", line 48, in iterate
    if resp['building']:
KeyError: 'building'
2022-03-22 15:07:52,936 - ERROR - unhandled exception:
Traceback (most recent call last):
  File "/mnt/filedump/git/jenot/src/jenot/qt/processor.py", line 30, in _run
    result = run(self.jenkins_base_url, self.user, self.token, self.build_part)
  File "/mnt/filedump/git/jenot/src/jenot/__init__.py", line 68, in run
    result, actual_url = iterate(url, USER, TOKEN)
  File "/mnt/filedump/git/jenot/src/jenot/__init__.py", line 48, in iterate
    if resp['building']:
KeyError: 'building'
NoneType: None
```

**Comment by Artalus** [comment]
Will *probably* be closed as a result of fixing #36. Need to check.
